### ISSUE TITLE
out of date templates

### ISSUE THREAD

**Issue by boldgrid-support** [BoldGrid/prime#33] opened 2019-03-12 18:59 UTC
**Describe the bug**
WooCommerce templates in V1 themes are flagged as out of date

**To Reproduce**
1. Install/Activate any V1 theme
2. Install/Activate WooCommerce
3. See the WooCommerce notice

**Comment by timelsass** [comment] 2019-03-19 22:59
went through v2 templates, and deprecated the majority of these templates as they are now handled with css variables and the new forms system in place.  

v1 is still using bootstrap classes to handle form inputs, so most of the updates for these will have to be manual.  As I went through each template, it doesn't appear like there's any issues being caused by this, so it will be a lower priority and fixed most likely when doing v1 bugfixes.

**Comment by nicolepaschen** [comment] 2019-09-24 15:56
Update: The following templates are out of date with Woo 3.7 and Inspirations 2.2

boldgrid-vacation/woocommerce/cart/cart-empty.php version 3.1.0 is out of date. The core version is 3.5.0,

boldgrid-vacation/woocommerce/cart/cart.php version 3.4.0 is out of date. The core version is 3.7.0,

boldgrid-vacation/woocommerce/checkout/cart-errors.php version 2.4.0 is out of date. The core version is 3.5.0,

boldgrid-vacation/woocommerce/checkout/form-billing.php version 3.0.9 is out of date. The core version is 3.6.0,

boldgrid-vacation/woocommerce/checkout/form-coupon.php version 3.4.0 is out of date. The core version is 3.4.4,

boldgrid-vacation/woocommerce/checkout/payment-method.php version 2.3.0 is out of date. The core version is 3.5.0,

boldgrid-vacation/woocommerce/checkout/payment.php version 3.4.0 is out of date. The core version is 3.5.3,

boldgrid-vacation/woocommerce/global/form-login.php version 3.3.0 is out of date. The core version is 3.6.0,

boldgrid-vacation/woocommerce/global/quantity-input.php version 3.4.0 is out of date. The core version is 3.6.0,

boldgrid-vacation/woocommerce/loop/orderby.php version 3.3.0 is out of date. The core version is 3.6.0,

boldgrid-vacation/woocommerce/myaccount/form-edit-account.php version 3.4.0 is out of date. The core version is 3.5.0,

boldgrid-vacation/woocommerce/myaccount/form-login.php version 3.4.0 is out of date. The core version is 3.6.0,

boldgrid-vacation/woocommerce/myaccount/form-lost-password.php version 3.4.0 is out of date. The core version is 3.5.2,

boldgrid-vacation/woocommerce/myaccount/form-reset-password.php version 3.4.0 is out of date. The core version is 3.5.5,

boldgrid-vacation/woocommerce/myaccount/orders.php version 3.2.0 is out of date. The core version is 3.7.0,

boldgrid-vacation/woocommerce/notices/error.php version 3.3.0 is out of date. The core version is 3.5.0,

boldgrid-vacation/woocommerce/notices/notice.php version 1.6.4 is out of date. The core version is 3.5.0,

boldgrid-vacation/woocommerce/notices/success.php version 3.3.0 is out of date. The core version is 3.5.0,

boldgrid-vacation/woocommerce/single-product/add-to-cart/variable.php version 3.4.0 is out of date. The core version is 3.5.5,

boldgrid-vacation/woocommerce/single-product-reviews.php version 3.2.0 is out of date. The core version is 3.6.0,

**Comment by nicolepaschen** [comment] 2019-11-13 21:26
boldgrid-vacation/woocommerce/cart/cart-empty.php version 3.1.0 is out of date. The core version is 3.5.0,
boldgrid-vacation/woocommerce/cart/cart.php version 3.4.0 is out of date. The core version is 3.8.0,

boldgrid-vacation/woocommerce/checkout/cart-errors.php version 2.4.0 is out of date. The core version is 3.5.0,
boldgrid-vacation/woocommerce/checkout/form-billing.php version 3.0.9 is out of date. The core version is 3.6.0,
boldgrid-vacation/woocommerce/checkout/form-coupon.php version 3.4.0 is out of date. The core version is 3.4.4,
boldgrid-vacation/woocommerce/checkout/payment-method.php version 2.3.0 is out of date. The core version is 3.5.0,
boldgrid-vacation/woocommerce/checkout/payment.php version 3.4.0 is out of date. The core version is 3.5.3,

boldgrid-vacation/woocommerce/global/form-login.php version 3.3.0 is out of date. The core version is 3.6.0,
boldgrid-vacation/woocommerce/global/quantity-input.php version 3.4.0 is out of date. The core version is 3.6.0,

boldgrid-vacation/woocommerce/loop/orderby.php version 3.3.0 is out of date. The core version is 3.6.0,

boldgrid-vacation/woocommerce/myaccount/form-edit-account.php version 3.4.0 is out of date. The core version is 3.5.0,
boldgrid-vacation/woocommerce/myaccount/form-login.php version 3.4.0 is out of date. The core version is 3.6.0,
boldgrid-vacation/woocommerce/myaccount/form-lost-password.php version 3.4.0 is out of date. The core version is 3.5.2,
boldgrid-vacation/woocommerce/myaccount/form-reset-password.php version 3.4.0 is out of date. The core version is 3.5.5,

boldgrid-vacation/woocommerce/myaccount/orders.php version 3.2.0 is out of date. The core version is 3.7.0,
boldgrid-vacation/woocommerce/notices/error.php version 3.3.0 is out of date. The core version is 3.5.0,
boldgrid-vacation/woocommerce/notices/notice.php version 1.6.4 is out of date. The core version is 3.5.0,
Now this is what's out of date: 

boldgrid-vacation/woocommerce/notices/success.php version 3.3.0 is out of date. The core version is 3.5.0,

boldgrid-vacation/woocommerce/single-product/add-to-cart/variable.php version 3.4.0 is out of date. The core version is 3.5.5,

boldgrid-vacation/woocommerce/single-product/tabs/tabs.php version 2.4.0 is out of date. The core version is 3.8.0,
boldgrid-vacation/woocommerce/single-product-reviews.php version 3.2.0 is out of date. The core version is 3.6.0,

**Comment by nicolepaschen** [comment] 2020-02-11 17:18
Crio: 
crio/woocommerce/notices/error.php version 3.5.2 is out of date. The core version is 3.9.0,
crio/woocommerce/notices/notice.php version 3.5.2 is out of date. The core version is 3.9.0,
crio/woocommerce/notices/success.php version 3.5.2 is out of date. The core version is 3.9.0,

**Comment by nicolepaschen** [comment] 2020-05-26 14:02
old ticket, closing to make a new current one

**Closed by nicolepaschen** 2020-05-26 14:02 UTC
